unit COLOR_ROTATE_UNIT;
interface
uses  Windows,OpenGL,FRMMAIN_UNIT, INIT_UNIT, OPTIONS_UNIT;


procedure ROT1(var ACTIVE_KUBIK:TKubik);
procedure ROT2(var ACTIVE_KUBIK:TKubik);
procedure ROT3(var ACTIVE_KUBIK:TKubik);
procedure ROT4(var ACTIVE_KUBIK:TKubik);
procedure ROT5(var ACTIVE_KUBIK:TKubik);
procedure ROT6(var ACTIVE_KUBIK:TKubik);

procedure ROT7(var ACTIVE_KUBIK:TKubik);
procedure ROT8(var ACTIVE_KUBIK:TKubik);
procedure ROT9(var ACTIVE_KUBIK:TKubik);
procedure ROT10(var ACTIVE_KUBIK:TKubik);
procedure ROT11(var ACTIVE_KUBIK:TKubik);
procedure ROT12(var ACTIVE_KUBIK:TKubik);

procedure ROT13(var ACTIVE_KUBIK:TKubik);
procedure ROT14(var ACTIVE_KUBIK:TKubik);
procedure ROT15(var ACTIVE_KUBIK:TKubik);
procedure ROT16(var ACTIVE_KUBIK:TKubik);
procedure ROT17(var ACTIVE_KUBIK:TKubik);
procedure ROT18(var ACTIVE_KUBIK:TKubik);

procedure ROT19(var ACTIVE_KUBIK:TKubik);
procedure ROT20(var ACTIVE_KUBIK:TKubik);
procedure ROT21(var ACTIVE_KUBIK:TKubik);
procedure ROT22(var ACTIVE_KUBIK:TKubik);
procedure ROT23(var ACTIVE_KUBIK:TKubik);
procedure ROT24(var ACTIVE_KUBIK:TKubik);
implementation
//œ
procedure ROT1(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
  tmp:=ACTIVE_KUBIK[1,1,1];
  ACTIVE_KUBIK[1,1,1].RIGHT:=ACTIVE_KUBIK[1,-1,1].RIGHT;
  ACTIVE_KUBIK[1,1,1].TOP:=ACTIVE_KUBIK[1,-1,1].FRONT;
  ACTIVE_KUBIK[1,1,1].FRONT:=ACTIVE_KUBIK[1,-1,1].BOTTOM;
  ACTIVE_KUBIK[1,1,1].elem:=ACTIVE_KUBIK[1,-1,1].elem;



  ACTIVE_KUBIK[1,-1,1].RIGHT:=ACTIVE_KUBIK[1,-1,-1].RIGHT;
  ACTIVE_KUBIK[1,-1,1].FRONT:=ACTIVE_KUBIK[1,-1,-1].BOTTOM;
  ACTIVE_KUBIK[1,-1,1].BOTTOM:=ACTIVE_KUBIK[1,-1,-1].BACK;
  ACTIVE_KUBIK[1,-1,1].elem:=ACTIVE_KUBIK[1,-1,-1].elem;

  ACTIVE_KUBIK[1,-1,-1].RIGHT:=ACTIVE_KUBIK[1,1,-1].RIGHT;
  ACTIVE_KUBIK[1,-1,-1].BOTTOM:=ACTIVE_KUBIK[1,1,-1].BACK;
  ACTIVE_KUBIK[1,-1,-1].BACK:=ACTIVE_KUBIK[1,1,-1].TOP;
  ACTIVE_KUBIK[1,-1,-1].elem:=ACTIVE_KUBIK[1,1,-1].elem;

  ACTIVE_KUBIK[1,1,-1].RIGHT:=tmp.RIGHT;
  ACTIVE_KUBIK[1,1,-1].BACK:=tmp.TOP;
  ACTIVE_KUBIK[1,1,-1].TOP:=tmp.FRONT;

  ACTIVE_KUBIK[1,1,-1].elem:=tmp.elem;
 //-1-1-1 ‚ 111

 //-1 -1 -1 ‚    1 1 -1


  tmp:=ACTIVE_KUBIK[1,1,0];
  ACTIVE_KUBIK[1,1,0].RIGHT:=ACTIVE_KUBIK[1,0,1].RIGHT;
  ACTIVE_KUBIK[1,1,0].TOP:=ACTIVE_KUBIK[1,0,1].FRONT;
  ACTIVE_KUBIK[1,1,0].elem:=ACTIVE_KUBIK[1,0,1].elem;

  ACTIVE_KUBIK[1,0,1].RIGHT:=ACTIVE_KUBIK[1,-1,0].RIGHT;
  ACTIVE_KUBIK[1,0,1].FRONT:=ACTIVE_KUBIK[1,-1,0].BOTTOM;
  ACTIVE_KUBIK[1,0,1].elem:=ACTIVE_KUBIK[1,-1,0].elem;

  ACTIVE_KUBIK[1,-1,0].RIGHT:=ACTIVE_KUBIK[1,0,-1].RIGHT;
  ACTIVE_KUBIK[1,-1,0].BOTTOM:=ACTIVE_KUBIK[1,0,-1].BACK;
  ACTIVE_KUBIK[1,-1,0].elem:=ACTIVE_KUBIK[1,0,-1].elem;

  ACTIVE_KUBIK[1,0,-1].RIGHT:=tmp.RIGHT;
  ACTIVE_KUBIK[1,0,-1].BACK:=tmp.TOP;
  ACTIVE_KUBIK[1,0,-1].elem:=tmp.elem;
end;
//œ–¿¬€… '
procedure ROT2(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
  tmp:=ACTIVE_KUBIK[1,1,1];
  ACTIVE_KUBIK[1,1,1].RIGHT:=ACTIVE_KUBIK[1,1,-1].RIGHT;
  ACTIVE_KUBIK[1,1,1].FRONT:=ACTIVE_KUBIK[1,1,-1].TOP;
  ACTIVE_KUBIK[1,1,1].TOP:=ACTIVE_KUBIK[1,1,-1].BACK;
  ACTIVE_KUBIK[1,1,1].elem:=ACTIVE_KUBIK[1,1,-1].elem;

  ACTIVE_KUBIK[1,1,-1].RIGHT:=ACTIVE_KUBIK[1,-1,-1].RIGHT;
  ACTIVE_KUBIK[1,1,-1].TOP:=ACTIVE_KUBIK[1,-1,-1].BACK;
  ACTIVE_KUBIK[1,1,-1].BACK:=ACTIVE_KUBIK[1,-1,-1].BOTTOM;
  ACTIVE_KUBIK[1,1,-1].elem:=ACTIVE_KUBIK[1,-1,-1].elem;

  ACTIVE_KUBIK[1,-1,-1].RIGHT:=ACTIVE_KUBIK[1,-1,1].RIGHT;
  ACTIVE_KUBIK[1,-1,-1].BACK:=ACTIVE_KUBIK[1,-1,1].BOTTOM;
  ACTIVE_KUBIK[1,-1,-1].BOTTOM:=ACTIVE_KUBIK[1,-1,1].FRONT;
  ACTIVE_KUBIK[1,-1,-1].elem:=ACTIVE_KUBIK[1,-1,1].elem;

  ACTIVE_KUBIK[1,-1,1].RIGHT:=tmp.RIGHT;
  ACTIVE_KUBIK[1,-1,1].BOTTOM:=tmp.FRONT;
  ACTIVE_KUBIK[1,-1,1].FRONT:=tmp.TOP;
  ACTIVE_KUBIK[1,-1,1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[1,1,0];
  ACTIVE_KUBIK[1,1,0].RIGHT:=ACTIVE_KUBIK[1,0,-1].RIGHT;
  ACTIVE_KUBIK[1,1,0].TOP:=ACTIVE_KUBIK[1,0,-1].BACK;
  ACTIVE_KUBIK[1,1,0].elem:=ACTIVE_KUBIK[1,0,-1].elem;

  ACTIVE_KUBIK[1,0,-1].RIGHT:=ACTIVE_KUBIK[1,-1,0].RIGHT;
  ACTIVE_KUBIK[1,0,-1].BACK:=ACTIVE_KUBIK[1,-1,0].BOTTOM;
  ACTIVE_KUBIK[1,0,-1].elem:=ACTIVE_KUBIK[1,-1,0].elem;

  ACTIVE_KUBIK[1,-1,0].RIGHT:=ACTIVE_KUBIK[1,0,1].RIGHT;
  ACTIVE_KUBIK[1,-1,0].BOTTOM:=ACTIVE_KUBIK[1,0,1].FRONT;
  ACTIVE_KUBIK[1,-1,0].elem:=ACTIVE_KUBIK[1,0,1].elem;

  ACTIVE_KUBIK[1,0,1].RIGHT:=tmp.RIGHT;
  ACTIVE_KUBIK[1,0,1].FRONT:=tmp.TOP;
  ACTIVE_KUBIK[1,0,1].elem:=tmp.elem;

  end;
//œ–¿¬€… —–≈ƒÕ»…
procedure ROT3(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
  tmp:=ACTIVE_KUBIK[0,1,1];
  ACTIVE_KUBIK[0,1,1].TOP:=ACTIVE_KUBIK[0,-1,1].FRONT;
  ACTIVE_KUBIK[0,1,1].FRONT:=ACTIVE_KUBIK[0,-1,1].BOTTOM;
  ACTIVE_KUBIK[0,1,1].elem:=ACTIVE_KUBIK[0,-1,1].elem;

  ACTIVE_KUBIK[0,-1,1].FRONT:=ACTIVE_KUBIK[0,-1,-1].BOTTOM;
  ACTIVE_KUBIK[0,-1,1].BOTTOM:=ACTIVE_KUBIK[0,-1,-1].BACK;
  ACTIVE_KUBIK[0,-1,1].elem:=ACTIVE_KUBIK[0,-1,-1].elem;

  ACTIVE_KUBIK[0,-1,-1].BOTTOM:=ACTIVE_KUBIK[0,1,-1].BACK;
  ACTIVE_KUBIK[0,-1,-1].BACK:=ACTIVE_KUBIK[0,1,-1].TOP;
  ACTIVE_KUBIK[0,-1,-1].elem:=ACTIVE_KUBIK[0,1,-1].elem;

  ACTIVE_KUBIK[0,1,-1].BACK:=tmp.TOP;
  ACTIVE_KUBIK[0,1,-1].TOP:=tmp.FRONT;
  ACTIVE_KUBIK[0,1,-1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,1,0];
  ACTIVE_KUBIK[0,1,0].TOP:=ACTIVE_KUBIK[0,0,1].FRONT;
  ACTIVE_KUBIK[0,1,0].elem:=ACTIVE_KUBIK[0,0,1].elem;

  ACTIVE_KUBIK[0,0,1].FRONT:=ACTIVE_KUBIK[0,-1,0].BOTTOM;
  ACTIVE_KUBIK[0,0,1].elem:=ACTIVE_KUBIK[0,-1,0].elem;

  ACTIVE_KUBIK[0,-1,0].BOTTOM:=ACTIVE_KUBIK[0,0,-1].BACK;
  ACTIVE_KUBIK[0,-1,0].elem:=ACTIVE_KUBIK[0,0,-1].elem;

  ACTIVE_KUBIK[0,0,-1].BACK:=tmp.TOP;
  ACTIVE_KUBIK[0,0,-1].elem:=tmp.elem;

end;
//œ–¿¬€… —–≈ƒÕ»… '
procedure ROT4(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
  tmp:=ACTIVE_KUBIK[0,1,1];
  ACTIVE_KUBIK[0,1,1].FRONT:=ACTIVE_KUBIK[0,1,-1].TOP;
  ACTIVE_KUBIK[0,1,1].TOP:=ACTIVE_KUBIK[0,1,-1].BACK;
  ACTIVE_KUBIK[0,1,1].elem:=ACTIVE_KUBIK[0,1,-1].elem;

  ACTIVE_KUBIK[0,1,-1].TOP:=ACTIVE_KUBIK[0,-1,-1].BACK;
  ACTIVE_KUBIK[0,1,-1].BACK:=ACTIVE_KUBIK[0,-1,-1].BOTTOM;
  ACTIVE_KUBIK[0,1,-1].elem:=ACTIVE_KUBIK[0,-1,-1].elem;

  ACTIVE_KUBIK[0,-1,-1].BACK:=ACTIVE_KUBIK[0,-1,1].BOTTOM;
  ACTIVE_KUBIK[0,-1,-1].BOTTOM:=ACTIVE_KUBIK[0,-1,1].FRONT;
  ACTIVE_KUBIK[0,-1,-1].elem:=ACTIVE_KUBIK[0,-1,1].elem;

  ACTIVE_KUBIK[0,-1,1].BOTTOM:=tmp.FRONT;
  ACTIVE_KUBIK[0,-1,1].FRONT:=tmp.TOP;
  ACTIVE_KUBIK[0,-1,1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,1,0];
  ACTIVE_KUBIK[0,1,0].TOP:=ACTIVE_KUBIK[0,0,-1].BACK;
  ACTIVE_KUBIK[0,1,0].elem:=ACTIVE_KUBIK[0,0,-1].elem;

  ACTIVE_KUBIK[0,0,-1].BACK:=ACTIVE_KUBIK[0,-1,0].BOTTOM;
  ACTIVE_KUBIK[0,0,-1].elem:=ACTIVE_KUBIK[0,-1,0].elem;

  ACTIVE_KUBIK[0,-1,0].BOTTOM:=ACTIVE_KUBIK[0,0,1].FRONT;
  ACTIVE_KUBIK[0,-1,0].elem:=ACTIVE_KUBIK[0,0,1].elem;

  ACTIVE_KUBIK[0,0,1].FRONT:=tmp.TOP;
  ACTIVE_KUBIK[0,0,1].elem:=tmp.elem;
end;
//À≈¬€… '
procedure ROT5(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
 tmp:=ACTIVE_KUBIK[-1,1,1];
  ACTIVE_KUBIK[-1,1,1].LEFT:=ACTIVE_KUBIK[-1,-1,1].LEFT;
  ACTIVE_KUBIK[-1,1,1].TOP:=ACTIVE_KUBIK[-1,-1,1].FRONT;
  ACTIVE_KUBIK[-1,1,1].FRONT:=ACTIVE_KUBIK[-1,-1,1].BOTTOM;
  ACTIVE_KUBIK[-1,1,1].elem:=ACTIVE_KUBIK[-1,-1,1].elem;

  ACTIVE_KUBIK[-1,-1,1].LEFT:=ACTIVE_KUBIK[-1,-1,-1].LEFT;
  ACTIVE_KUBIK[-1,-1,1].FRONT:=ACTIVE_KUBIK[-1,-1,-1].BOTTOM;
  ACTIVE_KUBIK[-1,-1,1].BOTTOM:=ACTIVE_KUBIK[-1,-1,-1].BACK;
  ACTIVE_KUBIK[-1,-1,1].elem:=ACTIVE_KUBIK[-1,-1,-1].elem;

  ACTIVE_KUBIK[-1,-1,-1].LEFT:=ACTIVE_KUBIK[-1,1,-1].LEFT;
  ACTIVE_KUBIK[-1,-1,-1].BOTTOM:=ACTIVE_KUBIK[-1,1,-1].BACK;
  ACTIVE_KUBIK[-1,-1,-1].BACK:=ACTIVE_KUBIK[-1,1,-1].TOP;
  ACTIVE_KUBIK[-1,-1,-1].elem:=ACTIVE_KUBIK[-1,1,-1].elem;

  ACTIVE_KUBIK[-1,1,-1].LEFT:=tmp.LEFT;
  ACTIVE_KUBIK[-1,1,-1].BACK:=tmp.TOP;
  ACTIVE_KUBIK[-1,1,-1].TOP:=tmp.FRONT;
  ACTIVE_KUBIK[-1,1,-1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[-1,1,0];
  ACTIVE_KUBIK[-1,1,0].LEFT:=ACTIVE_KUBIK[-1,0,1].LEFT;
  ACTIVE_KUBIK[-1,1,0].TOP:=ACTIVE_KUBIK[-1,0,1].FRONT;
  ACTIVE_KUBIK[-1,1,0].elem:=ACTIVE_KUBIK[-1,0,1].elem;

  ACTIVE_KUBIK[-1,0,1].LEFT:=ACTIVE_KUBIK[-1,-1,0].LEFT;
  ACTIVE_KUBIK[-1,0,1].FRONT:=ACTIVE_KUBIK[-1,-1,0].BOTTOM;
  ACTIVE_KUBIK[-1,0,1].elem:=ACTIVE_KUBIK[-1,-1,0].elem;

  ACTIVE_KUBIK[-1,-1,0].LEFT:=ACTIVE_KUBIK[-1,0,-1].LEFT;
  ACTIVE_KUBIK[-1,-1,0].BOTTOM:=ACTIVE_KUBIK[-1,0,-1].BACK;
  ACTIVE_KUBIK[-1,-1,0].elem:=ACTIVE_KUBIK[-1,0,-1].elem;

  ACTIVE_KUBIK[-1,0,-1].LEFT:=tmp.LEFT;
  ACTIVE_KUBIK[-1,0,-1].BACK:=tmp.TOP;
  ACTIVE_KUBIK[-1,0,-1].elem:=tmp.elem;
end;
//À≈¬€…
procedure ROT6(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
tmp:=ACTIVE_KUBIK[-1,1,1];
  ACTIVE_KUBIK[-1,1,1].LEFT:=ACTIVE_KUBIK[-1,1,-1].LEFT;
  ACTIVE_KUBIK[-1,1,1].FRONT:=ACTIVE_KUBIK[-1,1,-1].TOP;
  ACTIVE_KUBIK[-1,1,1].TOP:=ACTIVE_KUBIK[-1,1,-1].BACK;
  ACTIVE_KUBIK[-1,1,1].elem:=ACTIVE_KUBIK[-1,1,-1].elem;

  ACTIVE_KUBIK[-1,1,-1].LEFT:=ACTIVE_KUBIK[-1,-1,-1].LEFT;
  ACTIVE_KUBIK[-1,1,-1].TOP:=ACTIVE_KUBIK[-1,-1,-1].BACK;
  ACTIVE_KUBIK[-1,1,-1].BACK:=ACTIVE_KUBIK[-1,-1,-1].BOTTOM;
  ACTIVE_KUBIK[-1,1,-1].elem:=ACTIVE_KUBIK[-1,-1,-1].elem;

  ACTIVE_KUBIK[-1,-1,-1].LEFT:=ACTIVE_KUBIK[-1,-1,1].LEFT;
  ACTIVE_KUBIK[-1,-1,-1].BACK:=ACTIVE_KUBIK[-1,-1,1].BOTTOM;
  ACTIVE_KUBIK[-1,-1,-1].BOTTOM:=ACTIVE_KUBIK[-1,-1,1].FRONT;
  ACTIVE_KUBIK[-1,-1,-1].elem:=ACTIVE_KUBIK[-1,-1,1].elem;

  ACTIVE_KUBIK[-1,-1,1].LEFT:=tmp.LEFT;
  ACTIVE_KUBIK[-1,-1,1].BOTTOM:=tmp.FRONT;
  ACTIVE_KUBIK[-1,-1,1].FRONT:=tmp.TOP;
  ACTIVE_KUBIK[-1,-1,1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[-1,1,0];
  ACTIVE_KUBIK[-1,1,0].LEFT:=ACTIVE_KUBIK[-1,0,-1].LEFT;
  ACTIVE_KUBIK[-1,1,0].TOP:=ACTIVE_KUBIK[-1,0,-1].BACK;
  ACTIVE_KUBIK[-1,1,0].elem:=ACTIVE_KUBIK[-1,0,-1].elem;

  ACTIVE_KUBIK[-1,0,-1].LEFT:=ACTIVE_KUBIK[-1,-1,0].LEFT;
  ACTIVE_KUBIK[-1,0,-1].BACK:=ACTIVE_KUBIK[-1,-1,0].BOTTOM;
  ACTIVE_KUBIK[-1,0,-1].elem:=ACTIVE_KUBIK[-1,-1,0].elem;

  ACTIVE_KUBIK[-1,-1,0].LEFT:=ACTIVE_KUBIK[-1,0,1].LEFT;
  ACTIVE_KUBIK[-1,-1,0].BOTTOM:=ACTIVE_KUBIK[-1,0,1].FRONT;
  ACTIVE_KUBIK[-1,-1,0].elem:=ACTIVE_KUBIK[-1,0,1].elem;

  ACTIVE_KUBIK[-1,0,1].LEFT:=tmp.LEFT;
  ACTIVE_KUBIK[-1,0,1].FRONT:=tmp.TOP;
  ACTIVE_KUBIK[-1,0,1].elem:=tmp.elem;
end;
//‘–ŒÕ“
procedure ROT7(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
 tmp:=ACTIVE_KUBIK[1,1,1];
  ACTIVE_KUBIK[1,1,1].FRONT:=ACTIVE_KUBIK[-1,1,1].FRONT;
  ACTIVE_KUBIK[1,1,1].TOP:=ACTIVE_KUBIK[-1,1,1].LEFT;
  ACTIVE_KUBIK[1,1,1].RIGHT:=ACTIVE_KUBIK[-1,1,1].TOP;
  ACTIVE_KUBIK[1,1,1].elem:=ACTIVE_KUBIK[-1,1,1].elem;

  ACTIVE_KUBIK[-1,1,1].FRONT:=ACTIVE_KUBIK[-1,-1,1].FRONT;
  ACTIVE_KUBIK[-1,1,1].TOP:=ACTIVE_KUBIK[-1,-1,1].LEFT;
  ACTIVE_KUBIK[-1,1,1].LEFT:=ACTIVE_KUBIK[-1,-1,1].BOTTOM;
  ACTIVE_KUBIK[-1,1,1].elem:=ACTIVE_KUBIK[-1,-1,1].elem;

  ACTIVE_KUBIK[-1,-1,1].FRONT:=ACTIVE_KUBIK[1,-1,1].FRONT;
  ACTIVE_KUBIK[-1,-1,1].LEFT:=ACTIVE_KUBIK[1,-1,1].BOTTOM;
  ACTIVE_KUBIK[-1,-1,1].BOTTOM:=ACTIVE_KUBIK[1,-1,1].RIGHT;
  ACTIVE_KUBIK[-1,-1,1].elem:=ACTIVE_KUBIK[1,-1,1].elem;

  ACTIVE_KUBIK[1,-1,1].FRONT:=tmp.FRONT;
  ACTIVE_KUBIK[1,-1,1].BOTTOM:=tmp.Right;
  ACTIVE_KUBIK[1,-1,1].RIGHT:=tmp.TOP;
  ACTIVE_KUBIK[1,-1,1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,1,1];
  ACTIVE_KUBIK[0,1,1].FRONT:=ACTIVE_KUBIK[-1,0,1].FRONT;
  ACTIVE_KUBIK[0,1,1].TOP:=ACTIVE_KUBIK[-1,0,1].LEFT;
    ACTIVE_KUBIK[0,1,1].elem:=ACTIVE_KUBIK[-1,0,1].elem;

  ACTIVE_KUBIK[-1,0,1].FRONT:=ACTIVE_KUBIK[0,-1,1].FRONT;
  ACTIVE_KUBIK[-1,0,1].LEFT:=ACTIVE_KUBIK[0,-1,1].BOTTOM;
  ACTIVE_KUBIK[-1,0,1].elem:=ACTIVE_KUBIK[0,-1,1].elem;

  ACTIVE_KUBIK[0,-1,1].FRONT:=ACTIVE_KUBIK[1,0,1].FRONT;
  ACTIVE_KUBIK[0,-1,1].BOTTOM:=ACTIVE_KUBIK[1,0,1].RIGHT;
  ACTIVE_KUBIK[0,-1,1].elem:=ACTIVE_KUBIK[1,0,1].elem;

  ACTIVE_KUBIK[1,0,1].FRONT:=tmp.FRONT;
  ACTIVE_KUBIK[1,0,1].RIGHT:=tmp.TOP;
  ACTIVE_KUBIK[1,0,1].elem:=tmp.elem;
end;
//‘–ŒÕ“ '
procedure ROT8(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
  tmp:=ACTIVE_KUBIK[1,1,1];
  ACTIVE_KUBIK[1,1,1].FRONT:=ACTIVE_KUBIK[1,-1,1].FRONT ;
  ACTIVE_KUBIK[1,1,1].TOP:=ACTIVE_KUBIK[1,-1,1].RIGHT ;
  ACTIVE_KUBIK[1,1,1].RIGHT:=ACTIVE_KUBIK[1,-1,1].BOTTOM ;
  ACTIVE_KUBIK[1,1,1].elem:=ACTIVE_KUBIK[1,-1,1].elem ;

  ACTIVE_KUBIK[1,-1,1].FRONT:=ACTIVE_KUBIK[-1,-1,1].FRONT;
  ACTIVE_KUBIK[1,-1,1].RIGHT:=ACTIVE_KUBIK[-1,-1,1].BOTTOM;
  ACTIVE_KUBIK[1,-1,1].BOTTOM:=ACTIVE_KUBIK[-1,-1,1].LEFT;
  ACTIVE_KUBIK[1,-1,1].elem:=ACTIVE_KUBIK[-1,-1,1].elem;

  ACTIVE_KUBIK[-1,-1,1].FRONT:=ACTIVE_KUBIK[-1,1,1].FRONT;
  ACTIVE_KUBIK[-1,-1,1].BOTTOM:=ACTIVE_KUBIK[-1,1,1].LEFT;
  ACTIVE_KUBIK[-1,-1,1].LEFT:=ACTIVE_KUBIK[-1,1,1].TOP;
  ACTIVE_KUBIK[-1,-1,1].elem:=ACTIVE_KUBIK[-1,1,1].elem;

  ACTIVE_KUBIK[-1,1,1].FRONT:=tmp.FRONT;
  ACTIVE_KUBIK[-1,1,1].LEFT:=tmp.TOP;
  ACTIVE_KUBIK[-1,1,1].TOP:=tmp.RIGHT;
  ACTIVE_KUBIK[-1,1,1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,1,1];
  ACTIVE_KUBIK[0,1,1].FRONT:=ACTIVE_KUBIK[1,0,1].FRONT;
  ACTIVE_KUBIK[0,1,1].TOP:=ACTIVE_KUBIK[1,0,1].RIGHT;
  ACTIVE_KUBIK[0,1,1].elem:=ACTIVE_KUBIK[1,0,1].elem;

  ACTIVE_KUBIK[1,0,1].FRONT:=ACTIVE_KUBIK[0,-1,1].FRONT;
  ACTIVE_KUBIK[1,0,1].RIGHT:=ACTIVE_KUBIK[0,-1,1].BOTTOM;
  ACTIVE_KUBIK[1,0,1].elem:=ACTIVE_KUBIK[0,-1,1].elem;

  ACTIVE_KUBIK[0,-1,1].FRONT:= ACTIVE_KUBIK[-1,0,1].FRONT;
  ACTIVE_KUBIK[0,-1,1].BOTTOM:= ACTIVE_KUBIK[-1,0,1].LEFT;
  ACTIVE_KUBIK[0,-1,1].elem:= ACTIVE_KUBIK[-1,0,1].elem;

  ACTIVE_KUBIK[-1,0,1].FRONT:=tmp.FRONT;
  ACTIVE_KUBIK[-1,0,1].LEFT:=tmp.TOP;
  ACTIVE_KUBIK[-1,0,1].elem:=tmp.elem;

end;
//‘–ŒÕ“ —–≈ƒÕ»…
procedure ROT9(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
  tmp:=ACTIVE_KUBIK[1,1,0];
  ACTIVE_KUBIK[1,1,0].TOP:=ACTIVE_KUBIK[-1,1,0].LEFT;
  ACTIVE_KUBIK[1,1,0].RIGHT:=ACTIVE_KUBIK[-1,1,0].TOP;
  ACTIVE_KUBIK[1,1,0].elem:=ACTIVE_KUBIK[-1,1,0].elem;

  ACTIVE_KUBIK[-1,1,0].TOP:=ACTIVE_KUBIK[-1,-1,0].LEFT;
  ACTIVE_KUBIK[-1,1,0].LEFT:=ACTIVE_KUBIK[-1,-1,0].BOTTOM;
  ACTIVE_KUBIK[-1,1,0].elem:=ACTIVE_KUBIK[-1,-1,0].elem;

  ACTIVE_KUBIK[-1,-1,0].LEFT:=ACTIVE_KUBIK[1,-1,0].BOTTOM;
  ACTIVE_KUBIK[-1,-1,0].BOTTOM:=ACTIVE_KUBIK[1,-1,0].RIGHT;
  ACTIVE_KUBIK[-1,-1,0].elem:=ACTIVE_KUBIK[1,-1,0].elem;

  ACTIVE_KUBIK[1,-1,0].BOTTOM:=tmp.Right;
  ACTIVE_KUBIK[1,-1,0].RIGHT:=tmp.TOP;
  ACTIVE_KUBIK[1,-1,0].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,1,0];
  ACTIVE_KUBIK[0,1,0].TOP:=ACTIVE_KUBIK[-1,0,0].LEFT;
    ACTIVE_KUBIK[0,1,0].elem:=ACTIVE_KUBIK[-1,0,0].elem;

  ACTIVE_KUBIK[-1,0,0].LEFT:=ACTIVE_KUBIK[0,-1,0].BOTTOM;
  ACTIVE_KUBIK[-1,0,0].elem:=ACTIVE_KUBIK[0,-1,0].elem;

  ACTIVE_KUBIK[0,-1,0].BOTTOM:=ACTIVE_KUBIK[1,0,0].RIGHT;
  ACTIVE_KUBIK[0,-1,0].elem:=ACTIVE_KUBIK[1,0,0].elem;

  ACTIVE_KUBIK[1,0,0].RIGHT:=tmp.TOP;
  ACTIVE_KUBIK[1,0,0].elem:=tmp.elem;
end;

//‘–ŒÕ“ —–≈ƒÕ»… '
procedure ROT10(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
  tmp:=ACTIVE_KUBIK[1,1,0];
  ACTIVE_KUBIK[1,1,0].TOP:=ACTIVE_KUBIK[1,-1,0].RIGHT ;
  ACTIVE_KUBIK[1,1,0].RIGHT:=ACTIVE_KUBIK[1,-1,0].BOTTOM ;
  ACTIVE_KUBIK[1,1,0].elem:=ACTIVE_KUBIK[1,-1,0].elem ;

  ACTIVE_KUBIK[1,-1,0].RIGHT:=ACTIVE_KUBIK[-1,-1,0].BOTTOM;
  ACTIVE_KUBIK[1,-1,0].BOTTOM:=ACTIVE_KUBIK[-1,-1,0].LEFT;
  ACTIVE_KUBIK[1,-1,0].elem:=ACTIVE_KUBIK[-1,-1,0].elem;

  ACTIVE_KUBIK[-1,-1,0].BOTTOM:=ACTIVE_KUBIK[-1,1,0].LEFT;
  ACTIVE_KUBIK[-1,-1,0].LEFT:=ACTIVE_KUBIK[-1,1,0].TOP;
  ACTIVE_KUBIK[-1,-1,0].elem:=ACTIVE_KUBIK[-1,1,0].elem;

  ACTIVE_KUBIK[-1,1,0].LEFT:=tmp.TOP;
  ACTIVE_KUBIK[-1,1,0].TOP:=tmp.RIGHT;
  ACTIVE_KUBIK[-1,1,0].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,1,0];
  ACTIVE_KUBIK[0,1,0].TOP:=ACTIVE_KUBIK[1,0,0].RIGHT;
  ACTIVE_KUBIK[0,1,0].elem:=ACTIVE_KUBIK[1,0,0].elem;

  ACTIVE_KUBIK[1,0,0].RIGHT:=ACTIVE_KUBIK[0,-1,0].BOTTOM;
  ACTIVE_KUBIK[1,0,0].elem:=ACTIVE_KUBIK[0,-1,0].elem;

  ACTIVE_KUBIK[0,-1,0].BOTTOM:= ACTIVE_KUBIK[-1,0,0].LEFT;
  ACTIVE_KUBIK[0,-1,0].elem:= ACTIVE_KUBIK[-1,0,0].elem;

  ACTIVE_KUBIK[-1,0,0].LEFT:=tmp.TOP;
  ACTIVE_KUBIK[-1,0,0].elem:=tmp.elem;


end;
//“€À'
procedure ROT11(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
 tmp:=ACTIVE_KUBIK[1,1,-1];
  ACTIVE_KUBIK[1,1,-1].BACK:=ACTIVE_KUBIK[-1,1,-1].BACK;
  ACTIVE_KUBIK[1,1,-1].TOP:=ACTIVE_KUBIK[-1,1,-1].LEFT;
  ACTIVE_KUBIK[1,1,-1].RIGHT:=ACTIVE_KUBIK[-1,1,-1].TOP;
  ACTIVE_KUBIK[1,1,-1].elem:=ACTIVE_KUBIK[-1,1,-1].elem;

  ACTIVE_KUBIK[-1,1,-1].BACK:=ACTIVE_KUBIK[-1,-1,-1].BACK;
  ACTIVE_KUBIK[-1,1,-1].TOP:=ACTIVE_KUBIK[-1,-1,-1].LEFT;
  ACTIVE_KUBIK[-1,1,-1].LEFT:=ACTIVE_KUBIK[-1,-1,-1].BOTTOM;
  ACTIVE_KUBIK[-1,1,-1].elem:=ACTIVE_KUBIK[-1,-1,-1].elem;

  ACTIVE_KUBIK[-1,-1,-1].BACK:=ACTIVE_KUBIK[1,-1,-1].BACK;
  ACTIVE_KUBIK[-1,-1,-1].LEFT:=ACTIVE_KUBIK[1,-1,-1].BOTTOM;
  ACTIVE_KUBIK[-1,-1,-1].BOTTOM:=ACTIVE_KUBIK[1,-1,-1].RIGHT;
  ACTIVE_KUBIK[-1,-1,-1].elem:=ACTIVE_KUBIK[1,-1,-1].elem;

  ACTIVE_KUBIK[1,-1,-1].BACK:=tmp.BACK;
  ACTIVE_KUBIK[1,-1,-1].BOTTOM:=tmp.Right;
  ACTIVE_KUBIK[1,-1,-1].RIGHT:=tmp.TOP;
  ACTIVE_KUBIK[1,-1,-1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,1,-1];
  ACTIVE_KUBIK[0,1,-1].BACK:=ACTIVE_KUBIK[-1,0,-1].BACK;
  ACTIVE_KUBIK[0,1,-1].TOP:=ACTIVE_KUBIK[-1,0,-1].LEFT;
    ACTIVE_KUBIK[0,1,-1].elem:=ACTIVE_KUBIK[-1,0,-1].elem;

  ACTIVE_KUBIK[-1,0,-1].BACK:=ACTIVE_KUBIK[0,-1,-1].BACK;
  ACTIVE_KUBIK[-1,0,-1].LEFT:=ACTIVE_KUBIK[0,-1,-1].BOTTOM;
  ACTIVE_KUBIK[-1,0,-1].elem:=ACTIVE_KUBIK[0,-1,-1].elem;

  ACTIVE_KUBIK[0,-1,-1].BACK:=ACTIVE_KUBIK[1,0,-1].BACK;
  ACTIVE_KUBIK[0,-1,-1].BOTTOM:=ACTIVE_KUBIK[1,0,-1].RIGHT;
  ACTIVE_KUBIK[0,-1,-1].elem:=ACTIVE_KUBIK[1,0,-1].elem;

  ACTIVE_KUBIK[1,0,-1].BACK:=tmp.BACK;
  ACTIVE_KUBIK[1,0,-1].RIGHT:=tmp.TOP;
  ACTIVE_KUBIK[1,0,-1].elem:=tmp.elem;
end;
//“€À
procedure ROT12(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
tmp:=ACTIVE_KUBIK[1,1,-1];
  ACTIVE_KUBIK[1,1,-1].BACK:=ACTIVE_KUBIK[1,-1,-1].BACK ;
  ACTIVE_KUBIK[1,1,-1].TOP:=ACTIVE_KUBIK[1,-1,-1].RIGHT ;
  ACTIVE_KUBIK[1,1,-1].RIGHT:=ACTIVE_KUBIK[1,-1,-1].BOTTOM ;
  ACTIVE_KUBIK[1,1,-1].elem:=ACTIVE_KUBIK[1,-1,-1].elem ;

  ACTIVE_KUBIK[1,-1,-1].BACK:=ACTIVE_KUBIK[-1,-1,-1].BACK;
  ACTIVE_KUBIK[1,-1,-1].RIGHT:=ACTIVE_KUBIK[-1,-1,-1].BOTTOM;
  ACTIVE_KUBIK[1,-1,-1].BOTTOM:=ACTIVE_KUBIK[-1,-1,-1].LEFT;
  ACTIVE_KUBIK[1,-1,-1].elem:=ACTIVE_KUBIK[-1,-1,-1].elem;

  ACTIVE_KUBIK[-1,-1,-1].BACK:=ACTIVE_KUBIK[-1,1,-1].BACK;
  ACTIVE_KUBIK[-1,-1,-1].BOTTOM:=ACTIVE_KUBIK[-1,1,-1].LEFT;
  ACTIVE_KUBIK[-1,-1,-1].LEFT:=ACTIVE_KUBIK[-1,1,-1].TOP;
  ACTIVE_KUBIK[-1,-1,-1].elem:=ACTIVE_KUBIK[-1,1,-1].elem;

  ACTIVE_KUBIK[-1,1,-1].BACK:=tmp.BACK;
  ACTIVE_KUBIK[-1,1,-1].LEFT:=tmp.TOP;
  ACTIVE_KUBIK[-1,1,-1].TOP:=tmp.RIGHT;
  ACTIVE_KUBIK[-1,1,-1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,1,-1];
  ACTIVE_KUBIK[0,1,-1].BACK:=ACTIVE_KUBIK[1,0,-1].BACK;
  ACTIVE_KUBIK[0,1,-1].TOP:=ACTIVE_KUBIK[1,0,-1].RIGHT;
  ACTIVE_KUBIK[0,1,-1].elem:=ACTIVE_KUBIK[1,0,-1].elem;

  ACTIVE_KUBIK[1,0,-1].BACK:=ACTIVE_KUBIK[0,-1,-1].BACK;
  ACTIVE_KUBIK[1,0,-1].RIGHT:=ACTIVE_KUBIK[0,-1,-1].BOTTOM;
  ACTIVE_KUBIK[1,0,-1].elem:=ACTIVE_KUBIK[0,-1,-1].elem;

  ACTIVE_KUBIK[0,-1,-1].BACK:= ACTIVE_KUBIK[-1,0,-1].BACK;
  ACTIVE_KUBIK[0,-1,-1].BOTTOM:= ACTIVE_KUBIK[-1,0,-1].LEFT;
  ACTIVE_KUBIK[0,-1,-1].elem:= ACTIVE_KUBIK[-1,0,-1].elem;

  ACTIVE_KUBIK[-1,0,-1].BACK:=tmp.BACK;
  ACTIVE_KUBIK[-1,0,-1].LEFT:=tmp.TOP;
  ACTIVE_KUBIK[-1,0,-1].elem:=tmp.elem;
end;

//¬≈–’
procedure ROT13(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
  tmp:=ACTIVE_KUBIK[1,1,1];
  ACTIVE_KUBIK[1,1,1].TOP:=ACTIVE_KUBIK[1,1,-1].TOP ;
  ACTIVE_KUBIK[1,1,1].FRONT:=ACTIVE_KUBIK[1,1,-1].RIGHT ;
  ACTIVE_KUBIK[1,1,1].RIGHT:=ACTIVE_KUBIK[1,1,-1].BACK ;
  ACTIVE_KUBIK[1,1,1].elem:=ACTIVE_KUBIK[1,1,-1].elem ;

  ACTIVE_KUBIK[1,1,-1].TOP:=ACTIVE_KUBIK[-1,1,-1].TOP;
  ACTIVE_KUBIK[1,1,-1].RIGHT:=ACTIVE_KUBIK[-1,1,-1].BACK;
  ACTIVE_KUBIK[1,1,-1].BACK:=ACTIVE_KUBIK[-1,1,-1].LEFT;
  ACTIVE_KUBIK[1,1,-1].elem:=ACTIVE_KUBIK[-1,1,-1].elem;

  ACTIVE_KUBIK[-1,1,-1].TOP:=ACTIVE_KUBIK[-1,1,1].TOP;
  ACTIVE_KUBIK[-1,1,-1].BACK:=ACTIVE_KUBIK[-1,1,1].LEFT;
  ACTIVE_KUBIK[-1,1,-1].LEFT:=ACTIVE_KUBIK[-1,1,1].FRONT;
  ACTIVE_KUBIK[-1,1,-1].elem:=ACTIVE_KUBIK[-1,1,1].elem;

  ACTIVE_KUBIK[-1,1,1].TOP:=tmp.TOP;
  ACTIVE_KUBIK[-1,1,1].LEFT:=tmp.FRONT;
  ACTIVE_KUBIK[-1,1,1].FRONT:=tmp.RIGHT;
  ACTIVE_KUBIK[-1,1,1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,1,1];
  ACTIVE_KUBIK[0,1,1].TOP:=ACTIVE_KUBIK[1,1,0].TOP;
  ACTIVE_KUBIK[0,1,1].FRONT:=ACTIVE_KUBIK[1,1,0].RIGHT;
  ACTIVE_KUBIK[0,1,1].elem:=ACTIVE_KUBIK[1,1,0].elem;

  ACTIVE_KUBIK[1,1,0].TOP:=ACTIVE_KUBIK[0,1,-1].TOP;
  ACTIVE_KUBIK[1,1,0].RIGHT:=ACTIVE_KUBIK[0,1,-1].BACK;
  ACTIVE_KUBIK[1,1,0].elem:=ACTIVE_KUBIK[0,1,-1].elem;

  ACTIVE_KUBIK[0,1,-1].TOP:= ACTIVE_KUBIK[-1,1,0].TOP;
  ACTIVE_KUBIK[0,1,-1].BACK:= ACTIVE_KUBIK[-1,1,0].LEFT;
  ACTIVE_KUBIK[0,1,-1].elem:= ACTIVE_KUBIK[-1,1,0].elem;

  ACTIVE_KUBIK[-1,1,0].TOP:=tmp.TOP;
  ACTIVE_KUBIK[-1,1,0].LEFT:=tmp.FRONT;
  ACTIVE_KUBIK[-1,1,0].elem:=tmp.elem;
end;
//¬≈–’ '
procedure ROT14(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
  tmp:=ACTIVE_KUBIK[1,1,1];
  ACTIVE_KUBIK[1,1,1].TOP:=ACTIVE_KUBIK[-1,1,1].TOP ;
  ACTIVE_KUBIK[1,1,1].FRONT:=ACTIVE_KUBIK[-1,1,1].LEFT ;
  ACTIVE_KUBIK[1,1,1].RIGHT:=ACTIVE_KUBIK[-1,1,1].FRONT ;
  ACTIVE_KUBIK[1,1,1].elem:=ACTIVE_KUBIK[-1,1,1].elem ;

  ACTIVE_KUBIK[-1,1,1].TOP:=ACTIVE_KUBIK[-1,1,-1].TOP;
  ACTIVE_KUBIK[-1,1,1].LEFT:=ACTIVE_KUBIK[-1,1,-1].BACK;
  ACTIVE_KUBIK[-1,1,1].FRONT:=ACTIVE_KUBIK[-1,1,-1].LEFT;
  ACTIVE_KUBIK[-1,1,1].elem:=ACTIVE_KUBIK[-1,1,-1].elem;

  ACTIVE_KUBIK[-1,1,-1].TOP:=ACTIVE_KUBIK[1,1,-1].TOP;
  ACTIVE_KUBIK[-1,1,-1].BACK:=ACTIVE_KUBIK[1,1,-1].RIGHT;
  ACTIVE_KUBIK[-1,1,-1].LEFT:=ACTIVE_KUBIK[1,1,-1].BACK;
  ACTIVE_KUBIK[-1,1,-1].elem:=ACTIVE_KUBIK[1,1,-1].elem;

  ACTIVE_KUBIK[1,1,-1].TOP:=tmp.TOP;
  ACTIVE_KUBIK[1,1,-1].RIGHT:=tmp.FRONT;
  ACTIVE_KUBIK[1,1,-1].BACK:=tmp.RIGHT;
  ACTIVE_KUBIK[1,1,-1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,1,1];
  ACTIVE_KUBIK[0,1,1].TOP:=ACTIVE_KUBIK[-1,1,0].TOP;
  ACTIVE_KUBIK[0,1,1].FRONT:=ACTIVE_KUBIK[-1,1,0].LEFT;
  ACTIVE_KUBIK[0,1,1].elem:=ACTIVE_KUBIK[-1,1,0].elem;

  ACTIVE_KUBIK[-1,1,0].TOP:=ACTIVE_KUBIK[0,1,-1].TOP;
  ACTIVE_KUBIK[-1,1,0].LEFT:=ACTIVE_KUBIK[0,1,-1].BACK;
  ACTIVE_KUBIK[-1,1,0].elem:=ACTIVE_KUBIK[0,1,-1].elem;

  ACTIVE_KUBIK[0,1,-1].TOP:=ACTIVE_KUBIK[1,1,0].TOP ;
  ACTIVE_KUBIK[0,1,-1].BACK:=ACTIVE_KUBIK[1,1,0].RIGHT ;
  ACTIVE_KUBIK[0,1,-1].elem:=ACTIVE_KUBIK[1,1,0].elem ;

  ACTIVE_KUBIK[1,1,0].TOP:=tmp.TOP;
  ACTIVE_KUBIK[1,1,0].RIGHT:=tmp.FRONT;
  ACTIVE_KUBIK[1,1,0].elem:=tmp.elem;
end;
//—–≈ƒÕ»… ¬≈–’
procedure ROT15(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
  tmp:=ACTIVE_KUBIK[1,0,1];
  ACTIVE_KUBIK[1,0,1].FRONT:=ACTIVE_KUBIK[1,0,-1].RIGHT ;
  ACTIVE_KUBIK[1,0,1].RIGHT:=ACTIVE_KUBIK[1,0,-1].BACK ;
  ACTIVE_KUBIK[1,0,1].elem:=ACTIVE_KUBIK[1,0,-1].elem ;

  ACTIVE_KUBIK[1,0,-1].RIGHT:=ACTIVE_KUBIK[-1,0,-1].BACK;
  ACTIVE_KUBIK[1,0,-1].BACK:=ACTIVE_KUBIK[-1,0,-1].LEFT;
  ACTIVE_KUBIK[1,0,-1].elem:=ACTIVE_KUBIK[-1,0,-1].elem;

  ACTIVE_KUBIK[-1,0,-1].BACK:=ACTIVE_KUBIK[-1,0,1].LEFT;
  ACTIVE_KUBIK[-1,0,-1].LEFT:=ACTIVE_KUBIK[-1,0,1].FRONT;
  ACTIVE_KUBIK[-1,0,-1].elem:=ACTIVE_KUBIK[-1,0,1].elem;

  ACTIVE_KUBIK[-1,0,1].LEFT:=tmp.FRONT;
  ACTIVE_KUBIK[-1,0,1].FRONT:=tmp.RIGHT;
  ACTIVE_KUBIK[-1,0,1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,0,1];
  ACTIVE_KUBIK[0,0,1].FRONT:=ACTIVE_KUBIK[1,0,0].RIGHT;
  ACTIVE_KUBIK[0,0,1].elem:=ACTIVE_KUBIK[1,0,0].elem;

  ACTIVE_KUBIK[1,0,0].RIGHT:=ACTIVE_KUBIK[0,0,-1].BACK;
  ACTIVE_KUBIK[1,0,0].elem:=ACTIVE_KUBIK[0,0,-1].elem;

  ACTIVE_KUBIK[0,0,-1].BACK:= ACTIVE_KUBIK[-1,0,0].LEFT;
  ACTIVE_KUBIK[0,0,-1].elem:= ACTIVE_KUBIK[-1,0,0].elem;

  ACTIVE_KUBIK[-1,0,0].LEFT:=tmp.FRONT;
  ACTIVE_KUBIK[-1,0,0].elem:=tmp.elem;
end;

//—–≈ƒÕ»… ¬≈–’  '
procedure ROT16(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
  tmp:=ACTIVE_KUBIK[1,0,1];
  ACTIVE_KUBIK[1,0,1].FRONT:=ACTIVE_KUBIK[-1,0,1].LEFT ;
  ACTIVE_KUBIK[1,0,1].RIGHT:=ACTIVE_KUBIK[-1,0,1].FRONT ;
  ACTIVE_KUBIK[1,0,1].elem:=ACTIVE_KUBIK[-1,0,1].elem ;

  ACTIVE_KUBIK[-1,0,1].LEFT:=ACTIVE_KUBIK[-1,0,-1].BACK;
  ACTIVE_KUBIK[-1,0,1].FRONT:=ACTIVE_KUBIK[-1,0,-1].LEFT;
  ACTIVE_KUBIK[-1,0,1].elem:=ACTIVE_KUBIK[-1,0,-1].elem;

  ACTIVE_KUBIK[-1,0,-1].BACK:=ACTIVE_KUBIK[1,0,-1].RIGHT;
  ACTIVE_KUBIK[-1,0,-1].LEFT:=ACTIVE_KUBIK[1,0,-1].BACK;
  ACTIVE_KUBIK[-1,0,-1].elem:=ACTIVE_KUBIK[1,0,-1].elem;

  ACTIVE_KUBIK[1,0,-1].RIGHT:=tmp.FRONT;
  ACTIVE_KUBIK[1,0,-1].BACK:=tmp.RIGHT;
  ACTIVE_KUBIK[1,0,-1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,0,1];
  ACTIVE_KUBIK[0,0,1].FRONT:=ACTIVE_KUBIK[-1,0,0].LEFT;
  ACTIVE_KUBIK[0,0,1].elem:=ACTIVE_KUBIK[-1,0,0].elem;

  ACTIVE_KUBIK[-1,0,0].LEFT:=ACTIVE_KUBIK[0,0,-1].BACK;
  ACTIVE_KUBIK[-1,0,0].elem:=ACTIVE_KUBIK[0,0,-1].elem;

  ACTIVE_KUBIK[0,0,-1].BACK:=ACTIVE_KUBIK[1,0,0].RIGHT ;
  ACTIVE_KUBIK[0,0,-1].elem:=ACTIVE_KUBIK[1,0,0].elem ;

  ACTIVE_KUBIK[1,0,0].RIGHT:=tmp.FRONT;
  ACTIVE_KUBIK[1,0,0].elem:=tmp.elem;

end;
//Õ»« '
procedure ROT17(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
  tmp:=ACTIVE_KUBIK[1,-1,1];
  ACTIVE_KUBIK[1,-1,1].BOTTOM:=ACTIVE_KUBIK[1,-1,-1].BOTTOM ;
  ACTIVE_KUBIK[1,-1,1].FRONT:=ACTIVE_KUBIK[1,-1,-1].RIGHT ;
  ACTIVE_KUBIK[1,-1,1].RIGHT:=ACTIVE_KUBIK[1,-1,-1].BACK ;
  ACTIVE_KUBIK[1,-1,1].elem:=ACTIVE_KUBIK[1,-1,-1].elem ;

  ACTIVE_KUBIK[1,-1,-1].BOTTOM:=ACTIVE_KUBIK[-1,-1,-1].BOTTOM;
  ACTIVE_KUBIK[1,-1,-1].RIGHT:=ACTIVE_KUBIK[-1,-1,-1].BACK;
  ACTIVE_KUBIK[1,-1,-1].BACK:=ACTIVE_KUBIK[-1,-1,-1].LEFT;
  ACTIVE_KUBIK[1,-1,-1].elem:=ACTIVE_KUBIK[-1,-1,-1].elem;

  ACTIVE_KUBIK[-1,-1,-1].BOTTOM:=ACTIVE_KUBIK[-1,-1,1].BOTTOM;
  ACTIVE_KUBIK[-1,-1,-1].BACK:=ACTIVE_KUBIK[-1,-1,1].LEFT;
  ACTIVE_KUBIK[-1,-1,-1].LEFT:=ACTIVE_KUBIK[-1,-1,1].FRONT;
  ACTIVE_KUBIK[-1,-1,-1].elem:=ACTIVE_KUBIK[-1,-1,1].elem;

  ACTIVE_KUBIK[-1,-1,1].BOTTOM:=tmp.BOTTOM;
  ACTIVE_KUBIK[-1,-1,1].LEFT:=tmp.FRONT;
  ACTIVE_KUBIK[-1,-1,1].FRONT:=tmp.RIGHT;
  ACTIVE_KUBIK[-1,-1,1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,-1,1];
  ACTIVE_KUBIK[0,-1,1].BOTTOM:=ACTIVE_KUBIK[1,-1,0].BOTTOM;
  ACTIVE_KUBIK[0,-1,1].FRONT:=ACTIVE_KUBIK[1,-1,0].RIGHT;
  ACTIVE_KUBIK[0,-1,1].elem:=ACTIVE_KUBIK[1,-1,0].elem;

  ACTIVE_KUBIK[1,-1,0].BOTTOM:=ACTIVE_KUBIK[0,-1,-1].BOTTOM;
  ACTIVE_KUBIK[1,-1,0].RIGHT:=ACTIVE_KUBIK[0,-1,-1].BACK;
  ACTIVE_KUBIK[1,-1,0].elem:=ACTIVE_KUBIK[0,-1,-1].elem;

  ACTIVE_KUBIK[0,-1,-1].BOTTOM:= ACTIVE_KUBIK[-1,-1,0].BOTTOM;
  ACTIVE_KUBIK[0,-1,-1].BACK:= ACTIVE_KUBIK[-1,-1,0].LEFT;
  ACTIVE_KUBIK[0,-1,-1].elem:= ACTIVE_KUBIK[-1,-1,0].elem;

  ACTIVE_KUBIK[-1,-1,0].BOTTOM:=tmp.BOTTOM;
  ACTIVE_KUBIK[-1,-1,0].LEFT:=tmp.FRONT;
  ACTIVE_KUBIK[-1,-1,0].elem:=tmp.elem;
end;
//Õ»«
procedure ROT18(var ACTIVE_KUBIK:TKubik);
var tmp: Telement;
begin
 tmp:=ACTIVE_KUBIK[1,-1,1];
  ACTIVE_KUBIK[1,-1,1].BOTTOM:=ACTIVE_KUBIK[-1,-1,1].BOTTOM ;
  ACTIVE_KUBIK[1,-1,1].FRONT:=ACTIVE_KUBIK[-1,-1,1].LEFT ;
  ACTIVE_KUBIK[1,-1,1].RIGHT:=ACTIVE_KUBIK[-1,-1,1].FRONT ;
  ACTIVE_KUBIK[1,-1,1].elem:=ACTIVE_KUBIK[-1,-1,1].elem ;

  ACTIVE_KUBIK[-1,-1,1].BOTTOM:=ACTIVE_KUBIK[-1,-1,-1].BOTTOM;
  ACTIVE_KUBIK[-1,-1,1].LEFT:=ACTIVE_KUBIK[-1,-1,-1].BACK;
  ACTIVE_KUBIK[-1,-1,1].FRONT:=ACTIVE_KUBIK[-1,-1,-1].LEFT;
  ACTIVE_KUBIK[-1,-1,1].elem:=ACTIVE_KUBIK[-1,-1,-1].elem;

  ACTIVE_KUBIK[-1,-1,-1].BOTTOM:=ACTIVE_KUBIK[1,-1,-1].BOTTOM;
  ACTIVE_KUBIK[-1,-1,-1].BACK:=ACTIVE_KUBIK[1,-1,-1].RIGHT;
  ACTIVE_KUBIK[-1,-1,-1].LEFT:=ACTIVE_KUBIK[1,-1,-1].BACK;
  ACTIVE_KUBIK[-1,-1,-1].elem:=ACTIVE_KUBIK[1,-1,-1].elem;

  ACTIVE_KUBIK[1,-1,-1].BOTTOM:=tmp.BOTTOM;
  ACTIVE_KUBIK[1,-1,-1].RIGHT:=tmp.FRONT;
  ACTIVE_KUBIK[1,-1,-1].BACK:=tmp.RIGHT;
  ACTIVE_KUBIK[1,-1,-1].elem:=tmp.elem;

  tmp:=ACTIVE_KUBIK[0,-1,1];
  ACTIVE_KUBIK[0,-1,1].BOTTOM:=ACTIVE_KUBIK[-1,-1,0].BOTTOM;
  ACTIVE_KUBIK[0,-1,1].FRONT:=ACTIVE_KUBIK[-1,-1,0].LEFT;
  ACTIVE_KUBIK[0,-1,1].elem:=ACTIVE_KUBIK[-1,-1,0].elem;

  ACTIVE_KUBIK[-1,-1,0].BOTTOM:=ACTIVE_KUBIK[0,-1,-1].BOTTOM;
  ACTIVE_KUBIK[-1,-1,0].LEFT:=ACTIVE_KUBIK[0,-1,-1].BACK;
  ACTIVE_KUBIK[-1,-1,0].elem:=ACTIVE_KUBIK[0,-1,-1].elem;

  ACTIVE_KUBIK[0,-1,-1].BOTTOM:=ACTIVE_KUBIK[1,-1,0].BOTTOM ;
  ACTIVE_KUBIK[0,-1,-1].BACK:=ACTIVE_KUBIK[1,-1,0].RIGHT ;
  ACTIVE_KUBIK[0,-1,-1].elem:=ACTIVE_KUBIK[1,-1,0].elem ;

  ACTIVE_KUBIK[1,-1,0].BOTTOM:=tmp.BOTTOM;
  ACTIVE_KUBIK[1,-1,0].RIGHT:=tmp.FRONT;
  ACTIVE_KUBIK[1,-1,0].elem:=tmp.elem;
end;

procedure ROT19(var ACTIVE_KUBIK:TKubik);
begin
ROT7(ACTIVE_KUBIK);
ROT9(ACTIVE_KUBIK);
ROT11(ACTIVE_KUBIK);
end;

procedure ROT20(var ACTIVE_KUBIK:TKubik);
begin
ROT8(ACTIVE_KUBIK);
ROT10(ACTIVE_KUBIK);
ROT12(ACTIVE_KUBIK);
end;

procedure ROT21(var ACTIVE_KUBIK:TKubik);
begin
ROT1(ACTIVE_KUBIK);
ROT3(ACTIVE_KUBIK);
ROT5(ACTIVE_KUBIK);
end;

procedure ROT22(var ACTIVE_KUBIK:TKubik);
begin
ROT2(ACTIVE_KUBIK);
ROT4(ACTIVE_KUBIK);
ROT6(ACTIVE_KUBIK);
end;

procedure ROT23(var ACTIVE_KUBIK:TKubik);
begin
ROT14(ACTIVE_KUBIK);
ROT16(ACTIVE_KUBIK);
ROT18(ACTIVE_KUBIK);
end;

procedure ROT24(var ACTIVE_KUBIK:TKubik);
begin

ROT13(ACTIVE_KUBIK);
ROT15(ACTIVE_KUBIK);
ROT17(ACTIVE_KUBIK);
end;
end.
